### ISSUE TITLE
ST Hub stop sending MQTT notifications after about a day

### ISSUE THREAD

**Issue by theDontKnowGuy** [toddaustin07/MQTTDevices#5]
First and foremost, amazing job @toddaustin07. Not just on this project but generally speaking.
I have installed and am using the MQTT with around ten devices sending notifications to Mosquito. 
All good and well but around once a day MQTT stop getting events. Only a reboot of the Hub (Smartthings 2nd generation) resumes the MQTT events.
Any thoughts how can I debug it further?
Thanks in advance.
theDontKnowGuy

**Comment by toddaustin07** [comment]
Hi there - I'm really sorry for the problems you are having.  Is it still happening?

About 2 weeks ago I enhanced the recovery function in the driver for when it loses connection with the broker.  If that happens, it will try to re-connect every 15 seconds.

The best way to diagnose the issue is to get the SmartThings CLI and have logs running long term so you can try and catch it when the disconnects are happening.  It's hard to say what may be causing it.  

Some setups that are known to cause problems are having the broker run in a container or behind a VPN or firewall.

If you have a Windows machine available on your LAN, then you can install the CLI by downloading the Windows installer from this link:  https://github.com/SmartThingsCommunity/smartthings-cli/releases/download/%40smartthings%2Fcli%401.0.0/smartthings.msi

For some more information on how to use it, you can reference this post:  

https://community.smartthings.com/t/st-edge-breaking-boundaries-supporting-blue-iris-motion-alerts-and-shelly-wifi-motion-sensors/236540/43

Just ignore the OLD instructions there for downloading and installing.

**Comment by theDontKnowGuy** [comment]
So followed your instructions here. Here are the results:
When logging from the CLI, I see all the events as I would expect: 
<img width="1169" alt="Screenshot 2023-02-04 at 19 27 39" src="https://user-images.githubusercontent.com/40746333/216781300-fe890c3e-60fe-40d8-8f66-53b673509cf9.png">

However, no MQTT event is actually transmitted. 
Only after rebooting the hub, I start getting the MQTT events, for another few hours up to a day, then they stop appearing on the MQTT. 
Other events however, such as your smartapp application that receives them from the cloud on another topics, are working regardless, so it is not a MQTT issue. (But I want it to run locally ;-)

Thanks in advance for the help.

**Comment by toddaustin07** [comment]
A few questions:

* What kind of hub do you have?
* Is there anything unusual about your network configuration? 
* Is your hub and MQTT broker on the same sub-net?
* What do you see in the Status field in the Device Creator?
* What do you see in the Status field of the MQTT Switch device?

I don't see anything in your log showing that the switch state actually being sent.  Was this the entire log?  There should be more...

I would recommend that you set up a long term log-to-file so that you can try to catch the moment when the Edge driver may be disconnecting from the broker (if that is indeed what is happening).  You can use a command like this:
```
smartthings edge:drivers:logcat <driver id> --hub-address 192.168.1.xxx | tee -a mymqtt.log
```
This will both display the output in realtime on the console as well as store it in a file.  You'll want to Ctrl-c out of it after you are done capturing the log, to make sure that all data has been flushed to file.

**Comment by theDontKnowGuy** [comment]
Dear @toddaustin07 , Followed the instructions above I think I was able to narrow down and reproduce the issue, as can also demonstrated in the attached log.
I think the MQTT reporting stops in case the the MQTT server in unavailable for some time (like for a maintenance reboot or what not) and the connection never resumes until a reboot for the Smartthings Hub.
The following short log has four parts then:
1. everything works normally, MQTT receives events
2. I stopped the mosquito for say two minutes, driver complains on unable to connect
3. after the mosquito (and the RPI) is back online, it gets the events but the MQTT is not gettings messages.
4. I reboot the hub and then everything resumes to normal. 

What kind of hub do you have?   Smartthings 2 Generation
Is there anything unusual about your network configuration? The only thing is that I use Google Wifi behind the ISP router. No VPN, no other firewall.
Is your hub and MQTT broker on the same sub-net? Yes. everything is on the same subnet. 192.168.1.*
What do you see in the Status field in the Device Creator? Reconnecting... while MQTT is down and thereafter until Hun reboot
What do you see in the Status field of the MQTT Switch device? Nothing special (I am not subscribed there, only publishing As these are switches mimic Motion sensors).

link to logs: https://pastebin.com/NDVy5caH
password: toddrocks
Thanks much!!!

**Comment by toddaustin07** [comment]
Hello!- Thanks so much for the log.  It was really useful to see what was going on.

There are a couple things I had to fix:
1) your broker not only was unreachable at its port (e.g. mosquitto service was simply not running) , but there was **no route to the IP address itself**, which would usually mean your whole server was offline from the network.  This caused a 'no route to host' socket error which took nearly 20 seconds to get returned(!).  And the way the driver was coded, it gave up trying to retry the connection when it sees that error.  My original thinking on that was that if the IP address wasn't even valid, I wouldn't want the driver to be in an infinite retry loop every 15 seconds.  However after your experience, it's highlighting the fact that servers can go down, and I need to be able to recover from that.  So I'll change the code to keep retrying when a 'no route to host' is seen, and assume the user has the right IP address configured and it's just temporarily offline.

2) During the nearly 20 seconds it took for that socket error to happen, I see you tried to toggle the switch in the app.  This caused an error to occur since there was no active broker connection.  This didn't really harm anything, but I'm adding code to ignore the control more elegantly in these situations.

I have pushed out a driver update which I hope will cure your reconnection issues:  Version **2023-02-14T04:35:51.845376915**

Please try and reproduce the same situation.  You can systemctl stop mosquitto, but also do whatever caused the 'no route to host' error and see if things can successfully reconnect.  Remember that reconnects are attempted every 15 seconds.

**Comment by theDontKnowGuy** [comment]
This is absolutely fantastic. After a week of testing, I can confirm this solved the problem completely. Thank you so much.

**Comment by dr-boss** [comment]
I have same problem the MQTT Devices not reconnect after stop / start mosquitto.
